#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
    echo -e "\033[1;33m[\033[1;31mError\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
    rm $HOME/setup > /dev/null 2>&1; exit 0
}

select_vps_manager(){
    echo -e "\033[1;36mWELCOME TO \033[1;33mOFFICIAL ONEPESEWA VPS MANAGER\033[0m"
    echo -e "\n\033[1;33mSELECT VPS TO INSTALL\033[0m"
    echo "[\033[1;32m1\033[0m] \033[1;36mSSH VPS MANAGER\033[0m    [\033[1;32m2\033[0m] \033[1;36mSOCKSIP UDP SERVER\033[0m    [\033[1;32m3\033[0m] \033[1;36mBOTH\033[0m"
    read -p "Enter your choice: " choice
    case $choice in
        1)
            echo -e "\n\033[1;32mInstalling SSH SERVER ...\033[0m"
            apt-get update -y
            apt-get upgrade -y
            rm hehe*
            wget https://raw.githubusercontent.com/OfficialOnePesewa1990/Official-OnePesewa-VPS-Manager/main/setup
            chmod 777 setup
            ./setup
            ;;
        2)
            echo -e "\n\033[1;32mInstalling UDP server...\033[0m"
            wget https://raw.githubusercontent.com/rudi9999/SocksIP-udpServer/main/UDPserver.sh
            chmod +x UDPserver.sh
            ./UDPserver.sh
            ;;
        3)
            echo -e "\n\033[1;32mInstalling SSH and UDP servers...\033[0m"
            # Install SSH Server
            apt-get update -y
            apt-get upgrade -y
            rm hehe*
            wget https://raw.githubusercontent.com/OfficialOnePesewa1990/Official-OnePesewa-VPS-Manager/main/setup
            chmod 777 setup
            ./setup
            # Install UDP Server
            wget https://raw.githubusercontent.com/rudi9999/SocksIP-udpServer/main/UDPserver.sh
            chmod +x UDPserver.sh
            ./UDPserver.sh
            ;;
        *)
            echo -e "\n\033[1;31mInvalid choice. Please try again.\033[0m"
            select_vps_manager
            ;;
    esac
}

select_vps_manager
